---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/projects":
    get:
      summary: list projects
      tags:
      - project
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
    post:
      summary: create project
      tags:
      - project
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
              required:
              - title
              - description
  "/api/v1/projects/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show project
      tags:
      - project
      responses:
        '200':
          description: successful
    patch:
      summary: update project
      tags:
      - project
      responses:
        '200':
          description: successful
    put:
      summary: update project
      tags:
      - project
      responses:
        '200':
          description: successful
    delete:
      summary: delete project
      tags:
      - project
      responses:
        '200':
          description: successful
  "/api/v1/projects/{id}/get_all_tasks":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show project tasks
      tags:
      - project
      responses:
        '200':
          description: successful
  "/api/v1/tasks":
    get:
      summary: list tasks
      tags:
      - tasks
      responses:
        '200':
          description: successful
    post:
      summary: create task
      tags:
      - tasks
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                project_id:
                  type: integer
              required:
              - title
              - description
  "/api/v1/tasks/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show task
      tags:
      - tasks
      responses:
        '200':
          description: successful
    patch:
      summary: update task
      tags:
      - tasks
      responses:
        '200':
          description: successful
    put:
      summary: update task
      tags:
      - tasks
      responses:
        '200':
          description: successful
    delete:
      summary: delete task
      tags:
      - tasks
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
